version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Containerfile
    ports:
      - "3001:3001"
    environment:
      - DATABASE_URL=sqlite:///data/grimoire.db
    volumes:
      - backend_data:/app/data
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:3001/')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  frontend:
    build:
      context: ./frontend
      dockerfile: Containerfile
      args:
        - VITE_BACKEND_URL=http://localhost:3001
    ports:
      - "80:80"
    depends_on:
      backend:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  backend_data:
    driver: local