apiVersion: v1
kind: Service
metadata:
  name: {{ include "prompt-experimentation-tool.fullname" . }}
  labels:
    {{- include "prompt-experimentation-tool.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.frontendPort }}
      targetPort: frontend
      protocol: TCP
      name: frontend
    - port: {{ .Values.service.backendPort }}
      targetPort: backend
      protocol: TCP
      name: backend
  selector:
    {{- include "prompt-experimentation-tool.selectorLabels" . | nindent 4 }}